FROM centos:latest
RUN mkdir -p /var/run/sshd
RUN yum update -y
RUN yum install java -y
RUN yum install openssh-server -y
RUN mkdir /root/jenkins_node
RUN ssh-keygen -A
COPY ssh_config /etc/ssh/ssh_config
RUN echo root:redhat | chpasswd
CMD ["/usr/sbin/sshd", "-D"] && /bin/bash
RUN yum install sudo -y
